spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/subscription}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: subscription-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    default-schema: subscription-service
    create-schemas: true
